apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: checkmarx-home-assignment-euc1-flask-app
  name: checkmarx-home-assignment-euc1-flask-app
  namespace: checkmarx-home-assignment-euc1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: checkmarx-home-assignment-euc1-flask-app
  template:
    metadata:
      labels:
        app: checkmarx-home-assignment-euc1-flask-app
    spec:
      containers:
      - image: 329054710135.dkr.ecr.eu-central-1.amazonaws.com/checkmarkx_assignment:latest
        imagePullPolicy: IfNotPresent
        name: checkmarx-home-assignment-euc1-flask-app
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: checkmarx-home-assignment-euc1
  labels:
    app: checkmarx-home-assignment-euc1-flask-app
spec:
  type: LoadBalancer
  selector:
    app: checkmarx-home-assignment-euc1-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
